//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horario.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorarioEntities : DbContext
    {
        public HorarioEntities()
            : base("name=HorarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNOes { get; set; }
        public virtual DbSet<CarrerasDeDICA> CarrerasDeDICAs { get; set; }
        public virtual DbSet<CITA> CITAs { get; set; }
        public virtual DbSet<DiasDeEventoRecurrente> DiasDeEventoRecurrentes { get; set; }
        public virtual DbSet<DICA> DICAs { get; set; }
        public virtual DbSet<EVENTO> EVENTOes { get; set; }
        public virtual DbSet<EVENTO_RECURRENTE> EVENTO_RECURRENTE { get; set; }
        public virtual DbSet<PERSONA> PERSONAs { get; set; }
        public virtual DbSet<PERSONA_CEL> PERSONA_CEL { get; set; }
        public virtual DbSet<PERSONA_CORREO> PERSONA_CORREO { get; set; }
        public virtual DbSet<PROFESOR> PROFESORs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
